"""inicial

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 18:03:51.505309
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


UFS = [
    ("ac", "Acre", "Norte"), ("al", "Alagoas", "Nordeste"), ("am", "Amazonas", "Norte"), ("ap", "Amapá", "Norte"),
    ("ba", "Bahia", "Nordeste"), ("ce", "Ceará", "Nordeste"), ("df", "Distrito Federal", "Centro-Oeste"),
    ("es", "Espírito Santo", "Sudeste"), ("go", "Goiás", "Centro-Oeste"), ("ma", "Maranhão", "Nordeste"),
    ("mg", "Minas Gerais", "Sudeste"), ("ms", "Mato Grosso do Sul", "Centro-Oeste"),
    ("mt", "Mato Grosso", "Centro-Oeste"), ("pa", "Pará", "Norte"), ("pb", "Paraíba", "Nordeste"),
    ("pe", "Pernambuco", "Nordeste"), ("pi", "Piauí", "Nordeste"), ("pr", "Paraná", "Sul"),
    ("rj", "Rio de Janeiro", "Sudeste"), ("rn", "Rio Grande do Norte", "Nordeste"), ("ro", "Rondônia", "Norte"),
    ("rr", "Roraima", "Norte"), ("rs", "Rio Grande do Sul", "Sul"), ("sc", "Santa Catarina", "Sul"),
    ("se", "Sergipe", "Nordeste"), ("sp", "São Paulo", "Sudeste"), ("to", "Tocantins", "Norte"),
    ("zz", "Exterior", "Exterior"),
]


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boletim_urna',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('turno', sa.SmallInteger(), nullable=False),
    sa.Column('secao_id', sa.String(length=24), nullable=False),
    sa.Column('local_id', sa.String(length=24), nullable=True),
    sa.Column('zona_id', sa.String(length=16), nullable=False),
    sa.Column('municipio_id', sa.String(length=8), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('hash', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('totalizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emitido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capturado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eleitores_aptos', sa.Integer(), nullable=False),
    sa.Column('comparecimento', sa.Integer(), nullable=False),
    sa.Column('assinatura_ok', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(length=400), nullable=True),
    sa.Column('votos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boletim_urna')),
    sa.UniqueConstraint('turno', 'secao_id', name=op.f('uq_boletim_urna_turno_secao_id'))
    )
    op.create_index('ix_boletim_local_tempo', 'boletim_urna', ['turno', 'local_id', 'totalizado_em'], unique=False)
    op.create_index('ix_boletim_municipio', 'boletim_urna', ['turno', 'municipio_id'], unique=False)
    op.create_index(op.f('ix_boletim_urna_zona_id'), 'boletim_urna', ['zona_id'], unique=False)
    op.create_table('eleicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ambiente', sa.String(length=16), nullable=False),
    sa.Column('ciclo', sa.String(length=16), nullable=False),
    sa.Column('cd_pleito', sa.Integer(), nullable=False),
    sa.Column('cd_eleicao', sa.Integer(), nullable=False),
    sa.Column('cd_eleicao_t2', sa.Integer(), nullable=True),
    sa.Column('turno', sa.SmallInteger(), nullable=False),
    sa.Column('tipo', sa.String(length=16), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('data', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eleicao')),
    sa.UniqueConstraint('ambiente', 'cd_eleicao', name=op.f('uq_eleicao_ambiente_cd_eleicao'))
    )
    op.create_table('evento',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('turno', sa.SmallInteger(), nullable=False),
    sa.Column('tipo', sa.String(length=32), nullable=False),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cd_cargo', sa.SmallInteger(), nullable=True),
    sa.Column('nivel', sa.String(length=10), nullable=True),
    sa.Column('recorte_id', sa.String(length=24), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evento'))
    )
    op.create_index('ix_evento_turno_ocorrido', 'evento', ['turno', 'ocorrido_em'], unique=False)
    op.create_table('progresso_atual',
    sa.Column('turno', sa.SmallInteger(), nullable=False),
    sa.Column('nivel', sa.String(length=10), nullable=False),
    sa.Column('recorte_id', sa.String(length=24), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('idg', sa.BigInteger(), nullable=False),
    sa.Column('totalizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capturado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('andamento', sa.String(length=4), nullable=False),
    sa.Column('secoes_total', sa.Integer(), nullable=False),
    sa.Column('secoes_totalizadas', sa.Integer(), nullable=False),
    sa.Column('pct_secoes', sa.Float(), nullable=False),
    sa.Column('eleitorado', sa.Integer(), nullable=False),
    sa.Column('comparecimento', sa.Integer(), nullable=False),
    sa.Column('pct_comparecimento', sa.Float(), nullable=False),
    sa.Column('municipios_finalizados', sa.Integer(), nullable=False),
    sa.Column('municipios_parciais', sa.Integer(), nullable=False),
    sa.Column('municipios_nao_recebidos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('turno', 'nivel', 'recorte_id', name=op.f('pk_progresso_atual'))
    )
    op.create_table('resultado_atual',
    sa.Column('turno', sa.SmallInteger(), nullable=False),
    sa.Column('cd_cargo', sa.SmallInteger(), nullable=False),
    sa.Column('nivel', sa.String(length=10), nullable=False),
    sa.Column('recorte_id', sa.String(length=24), nullable=False),
    sa.Column('eleicao_id', sa.Integer(), nullable=False),
    sa.Column('pai_id', sa.String(length=24), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('idg', sa.BigInteger(), nullable=False),
    sa.Column('totalizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capturado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('jws_verificado', sa.Boolean(), nullable=False),
    sa.Column('fonte', sa.String(length=8), nullable=False),
    sa.Column('arquivo', sa.String(length=300), nullable=True),
    sa.Column('eleitorado', sa.Integer(), nullable=False),
    sa.Column('eleitorado_apurado', sa.Integer(), nullable=False),
    sa.Column('secoes_total', sa.Integer(), nullable=False),
    sa.Column('secoes_totalizadas', sa.Integer(), nullable=False),
    sa.Column('pct_secoes', sa.Float(), nullable=False),
    sa.Column('comparecimento', sa.Integer(), nullable=False),
    sa.Column('pct_comparecimento', sa.Float(), nullable=False),
    sa.Column('abstencao', sa.Integer(), nullable=False),
    sa.Column('pct_abstencao', sa.Float(), nullable=False),
    sa.Column('votos_total', sa.Integer(), nullable=False),
    sa.Column('votos_validos', sa.Integer(), nullable=False),
    sa.Column('pct_validos', sa.Float(), nullable=False),
    sa.Column('brancos', sa.Integer(), nullable=False),
    sa.Column('pct_brancos', sa.Float(), nullable=False),
    sa.Column('nulos', sa.Integer(), nullable=False),
    sa.Column('pct_nulos', sa.Float(), nullable=False),
    sa.Column('matematicamente_definido', sa.Boolean(), nullable=False),
    sa.Column('totalizacao_final', sa.Boolean(), nullable=False),
    sa.Column('lider_sqcand', sa.String(length=20), nullable=True),
    sa.Column('lider_votos', sa.Integer(), nullable=False),
    sa.Column('lider_pct', sa.Float(), nullable=False),
    sa.Column('segundo_sqcand', sa.String(length=20), nullable=True),
    sa.Column('segundo_votos', sa.Integer(), nullable=False),
    sa.Column('segundo_pct', sa.Float(), nullable=False),
    sa.Column('margem_pp', sa.Float(), nullable=False),
    sa.Column('partido_lider', sa.String(length=160), nullable=True),
    sa.Column('candidatos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agremiacoes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('turno', 'cd_cargo', 'nivel', 'recorte_id', name=op.f('pk_resultado_atual'))
    )
    op.create_index('ix_resultado_atual_pai', 'resultado_atual', ['turno', 'cd_cargo', 'nivel', 'pai_id'], unique=False)
    op.create_table('resultado_local',
    sa.Column('turno', sa.SmallInteger(), nullable=False),
    sa.Column('cd_cargo', sa.SmallInteger(), nullable=False),
    sa.Column('local_id', sa.String(length=24), nullable=False),
    sa.Column('municipio_id', sa.String(length=8), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('secoes_total', sa.Integer(), nullable=False),
    sa.Column('secoes_apuradas', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('comparecimento', sa.Integer(), nullable=False),
    sa.Column('votos_validos', sa.Integer(), nullable=False),
    sa.Column('brancos', sa.Integer(), nullable=False),
    sa.Column('nulos', sa.Integer(), nullable=False),
    sa.Column('lider_sqcand', sa.String(length=20), nullable=True),
    sa.Column('lider_pct', sa.Float(), nullable=False),
    sa.Column('margem_pp', sa.Float(), nullable=False),
    sa.Column('votos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('turno', 'cd_cargo', 'local_id', name=op.f('pk_resultado_local'))
    )
    op.create_index('ix_resultado_local_municipio', 'resultado_local', ['turno', 'cd_cargo', 'municipio_id'], unique=False)
    op.create_table('snapshot_progresso',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('turno', sa.SmallInteger(), nullable=False),
    sa.Column('nivel', sa.String(length=10), nullable=False),
    sa.Column('recorte_id', sa.String(length=24), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('idg', sa.BigInteger(), nullable=False),
    sa.Column('totalizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capturado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('andamento', sa.String(length=4), nullable=False),
    sa.Column('secoes_total', sa.Integer(), nullable=False),
    sa.Column('secoes_totalizadas', sa.Integer(), nullable=False),
    sa.Column('pct_secoes', sa.Float(), nullable=False),
    sa.Column('eleitorado', sa.Integer(), nullable=False),
    sa.Column('comparecimento', sa.Integer(), nullable=False),
    sa.Column('pct_comparecimento', sa.Float(), nullable=False),
    sa.Column('municipios_finalizados', sa.Integer(), nullable=False),
    sa.Column('municipios_parciais', sa.Integer(), nullable=False),
    sa.Column('municipios_nao_recebidos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshot_progresso')),
    sa.UniqueConstraint('turno', 'nivel', 'recorte_id', 'idg', name=op.f('uq_snapshot_progresso_turno_nivel_recorte_id_idg'))
    )
    op.create_index('ix_snapshot_progresso_tempo', 'snapshot_progresso', ['turno', 'nivel', 'recorte_id', 'totalizado_em'], unique=False)
    op.create_table('snapshot_resultado',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('eleicao_id', sa.Integer(), nullable=False),
    sa.Column('turno', sa.SmallInteger(), nullable=False),
    sa.Column('cd_cargo', sa.SmallInteger(), nullable=False),
    sa.Column('nivel', sa.String(length=10), nullable=False),
    sa.Column('recorte_id', sa.String(length=24), nullable=False),
    sa.Column('pai_id', sa.String(length=24), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('idg', sa.BigInteger(), nullable=False),
    sa.Column('totalizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capturado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('jws_verificado', sa.Boolean(), nullable=False),
    sa.Column('fonte', sa.String(length=8), nullable=False),
    sa.Column('arquivo', sa.String(length=300), nullable=True),
    sa.Column('eleitorado', sa.Integer(), nullable=False),
    sa.Column('eleitorado_apurado', sa.Integer(), nullable=False),
    sa.Column('secoes_total', sa.Integer(), nullable=False),
    sa.Column('secoes_totalizadas', sa.Integer(), nullable=False),
    sa.Column('pct_secoes', sa.Float(), nullable=False),
    sa.Column('comparecimento', sa.Integer(), nullable=False),
    sa.Column('pct_comparecimento', sa.Float(), nullable=False),
    sa.Column('abstencao', sa.Integer(), nullable=False),
    sa.Column('pct_abstencao', sa.Float(), nullable=False),
    sa.Column('votos_total', sa.Integer(), nullable=False),
    sa.Column('votos_validos', sa.Integer(), nullable=False),
    sa.Column('pct_validos', sa.Float(), nullable=False),
    sa.Column('brancos', sa.Integer(), nullable=False),
    sa.Column('pct_brancos', sa.Float(), nullable=False),
    sa.Column('nulos', sa.Integer(), nullable=False),
    sa.Column('pct_nulos', sa.Float(), nullable=False),
    sa.Column('matematicamente_definido', sa.Boolean(), nullable=False),
    sa.Column('totalizacao_final', sa.Boolean(), nullable=False),
    sa.Column('lider_sqcand', sa.String(length=20), nullable=True),
    sa.Column('lider_votos', sa.Integer(), nullable=False),
    sa.Column('lider_pct', sa.Float(), nullable=False),
    sa.Column('segundo_sqcand', sa.String(length=20), nullable=True),
    sa.Column('segundo_votos', sa.Integer(), nullable=False),
    sa.Column('segundo_pct', sa.Float(), nullable=False),
    sa.Column('margem_pp', sa.Float(), nullable=False),
    sa.Column('partido_lider', sa.String(length=160), nullable=True),
    sa.Column('candidatos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agremiacoes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshot_resultado')),
    sa.UniqueConstraint('turno', 'cd_cargo', 'nivel', 'recorte_id', 'idg', name=op.f('uq_snapshot_resultado_turno_cd_cargo_nivel_recorte_id_idg'))
    )
    op.create_index('ix_snapshot_busca_tempo', 'snapshot_resultado', ['turno', 'cd_cargo', 'nivel', 'recorte_id', 'totalizado_em'], unique=False)
    op.create_index('ix_snapshot_pai_tempo', 'snapshot_resultado', ['turno', 'cd_cargo', 'nivel', 'pai_id', 'totalizado_em'], unique=False)
    op.create_table('uf',
    sa.Column('sigla', sa.String(length=2), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('regiao', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('sigla', name=op.f('pk_uf'))
    )
    uf_tabela = sa.table("uf", sa.column("sigla", sa.String), sa.column("nome", sa.String), sa.column("regiao", sa.String))
    op.bulk_insert(uf_tabela, [{"sigla": a, "nome": b, "regiao": c} for a, b, c in UFS])
    op.create_table('usuario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('email', name=op.f('uq_usuario_email'))
    )
    op.create_table('alerta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=32), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('disparado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_alerta_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerta'))
    )
    op.create_index(op.f('ix_alerta_usuario_id'), 'alerta', ['usuario_id'], unique=False)
    op.create_table('candidato',
    sa.Column('sqcand', sa.String(length=20), nullable=False),
    sa.Column('eleicao_id', sa.Integer(), nullable=False),
    sa.Column('turno', sa.SmallInteger(), nullable=False),
    sa.Column('cd_cargo', sa.SmallInteger(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('nome_urna', sa.String(length=120), nullable=False),
    sa.Column('partido_sigla', sa.String(length=20), nullable=False),
    sa.Column('partido_numero', sa.Integer(), nullable=False),
    sa.Column('agremiacao', sa.String(length=160), nullable=False),
    sa.Column('cor', sa.String(length=9), nullable=False),
    sa.Column('vices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('situacao_geral', sa.String(length=32), nullable=False),
    sa.Column('eleito', sa.Boolean(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eleicao_id'], ['eleicao.id'], name=op.f('fk_candidato_eleicao_id_eleicao'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sqcand', name=op.f('pk_candidato'))
    )
    op.create_index('ix_candidato_cargo_uf_numero', 'candidato', ['turno', 'cd_cargo', 'uf', 'numero'], unique=False)
    op.create_table('eleicao_cargo',
    sa.Column('eleicao_id', sa.Integer(), nullable=False),
    sa.Column('cd_cargo', sa.SmallInteger(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('sistema', sa.String(length=16), nullable=False),
    sa.Column('abrangencia', sa.String(length=4), nullable=False),
    sa.Column('vagas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eleicao_id'], ['eleicao.id'], name=op.f('fk_eleicao_cargo_eleicao_id_eleicao'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('eleicao_id', 'cd_cargo', name=op.f('pk_eleicao_cargo'))
    )
    op.create_table('favorito',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=16), nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('rotulo', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_favorito_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'tipo', 'ref', name=op.f('pk_favorito'))
    )
    op.create_table('municipio',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cd_tse', sa.Integer(), nullable=False),
    sa.Column('cd_ibge', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('capital', sa.Boolean(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('eleitorado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uf'], ['uf.sigla'], name=op.f('fk_municipio_uf_uf')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_municipio'))
    )
    op.create_index(op.f('ix_municipio_cd_ibge'), 'municipio', ['cd_ibge'], unique=False)
    op.create_index(op.f('ix_municipio_uf'), 'municipio', ['uf'], unique=False)
    op.create_table('painel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('padrao', sa.Boolean(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_painel_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_painel'))
    )
    op.create_index(op.f('ix_painel_usuario_id'), 'painel', ['usuario_id'], unique=False)
    op.create_table('preferencia',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('dados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_preferencia_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', name=op.f('pk_preferencia'))
    )
    op.create_table('compartilhamento',
    sa.Column('token', sa.String(length=40), nullable=False),
    sa.Column('painel_id', sa.Uuid(), nullable=False),
    sa.Column('modo', sa.String(length=16), nullable=False),
    sa.Column('tempo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['painel_id'], ['painel.id'], name=op.f('fk_compartilhamento_painel_id_painel'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_compartilhamento'))
    )
    op.create_index(op.f('ix_compartilhamento_painel_id'), 'compartilhamento', ['painel_id'], unique=False)
    op.create_table('local_votacao',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('municipio_id', sa.String(length=8), nullable=False),
    sa.Column('zona_id', sa.String(length=16), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('endereco', sa.String(length=250), nullable=True),
    sa.Column('bairro', sa.String(length=120), nullable=True),
    sa.Column('cep', sa.String(length=12), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('aproximado', sa.Boolean(), nullable=False),
    sa.Column('eleitores_aptos', sa.Integer(), nullable=False),
    sa.Column('qtd_secoes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], name=op.f('fk_local_votacao_municipio_id_municipio'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_local_votacao'))
    )
    op.create_index('ix_local_votacao_lat_lon', 'local_votacao', ['lat', 'lon'], unique=False)
    op.create_index(op.f('ix_local_votacao_municipio_id'), 'local_votacao', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_local_votacao_uf'), 'local_votacao', ['uf'], unique=False)
    op.create_index(op.f('ix_local_votacao_zona_id'), 'local_votacao', ['zona_id'], unique=False)
    op.create_table('secao',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('municipio_id', sa.String(length=8), nullable=False),
    sa.Column('zona_id', sa.String(length=16), nullable=False),
    sa.Column('local_id', sa.String(length=24), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('eleitores_aptos', sa.Integer(), nullable=True),
    sa.Column('agregadora', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], name=op.f('fk_secao_municipio_id_municipio'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secao'))
    )
    op.create_index(op.f('ix_secao_local_id'), 'secao', ['local_id'], unique=False)
    op.create_index(op.f('ix_secao_municipio_id'), 'secao', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_secao_uf'), 'secao', ['uf'], unique=False)
    op.create_index(op.f('ix_secao_zona_id'), 'secao', ['zona_id'], unique=False)
    op.create_table('zona',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('municipio_id', sa.String(length=8), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], name=op.f('fk_zona_municipio_id_municipio'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zona'))
    )
    op.create_index(op.f('ix_zona_municipio_id'), 'zona', ['municipio_id'], unique=False)
    op.execute("CREATE INDEX ix_municipio_nome_trgm ON municipio USING gin (lower(nome) gin_trgm_ops)")
    op.execute("CREATE INDEX ix_local_nome_trgm ON local_votacao USING gin (lower(nome) gin_trgm_ops)")
    op.execute("CREATE INDEX ix_candidato_nome_trgm ON candidato USING gin (lower(nome_urna) gin_trgm_ops)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zona_municipio_id'), table_name='zona')
    op.drop_table('zona')
    op.drop_index(op.f('ix_secao_zona_id'), table_name='secao')
    op.drop_index(op.f('ix_secao_uf'), table_name='secao')
    op.drop_index(op.f('ix_secao_municipio_id'), table_name='secao')
    op.drop_index(op.f('ix_secao_local_id'), table_name='secao')
    op.drop_table('secao')
    op.drop_index(op.f('ix_local_votacao_zona_id'), table_name='local_votacao')
    op.drop_index(op.f('ix_local_votacao_uf'), table_name='local_votacao')
    op.drop_index(op.f('ix_local_votacao_municipio_id'), table_name='local_votacao')
    op.drop_index('ix_local_votacao_lat_lon', table_name='local_votacao')
    op.drop_table('local_votacao')
    op.drop_index(op.f('ix_compartilhamento_painel_id'), table_name='compartilhamento')
    op.drop_table('compartilhamento')
    op.drop_table('preferencia')
    op.drop_index(op.f('ix_painel_usuario_id'), table_name='painel')
    op.drop_table('painel')
    op.drop_index(op.f('ix_municipio_uf'), table_name='municipio')
    op.drop_index(op.f('ix_municipio_cd_ibge'), table_name='municipio')
    op.drop_table('municipio')
    op.drop_table('favorito')
    op.drop_table('eleicao_cargo')
    op.drop_index('ix_candidato_cargo_uf_numero', table_name='candidato')
    op.drop_table('candidato')
    op.drop_index(op.f('ix_alerta_usuario_id'), table_name='alerta')
    op.drop_table('alerta')
    op.drop_table('usuario')
    op.drop_table('uf')
    op.drop_index('ix_snapshot_pai_tempo', table_name='snapshot_resultado')
    op.drop_index('ix_snapshot_busca_tempo', table_name='snapshot_resultado')
    op.drop_table('snapshot_resultado')
    op.drop_index('ix_snapshot_progresso_tempo', table_name='snapshot_progresso')
    op.drop_table('snapshot_progresso')
    op.drop_index('ix_resultado_local_municipio', table_name='resultado_local')
    op.drop_table('resultado_local')
    op.drop_index('ix_resultado_atual_pai', table_name='resultado_atual')
    op.drop_table('resultado_atual')
    op.drop_table('progresso_atual')
    op.drop_index('ix_evento_turno_ocorrido', table_name='evento')
    op.drop_table('evento')
    op.drop_table('eleicao')
    op.drop_index(op.f('ix_boletim_urna_zona_id'), table_name='boletim_urna')
    op.drop_index('ix_boletim_municipio', table_name='boletim_urna')
    op.drop_index('ix_boletim_local_tempo', table_name='boletim_urna')
    op.drop_table('boletim_urna')
    # ### end Alembic commands ###
