import {
  IconBuildingCommunity,
  IconCalendarEvent,
  IconChartArcs,
  IconChartDonut,
  IconChartLine,
  IconClock,
  IconColumns,
  IconFileCertificate,
  IconGridDots,
  IconListNumbers,
  IconMap2,
  IconNotes,
  IconNumber,
  IconSchool,
  IconTable,
  IconUserCircle,
} from "@tabler/icons-react";
import type { TipoWidget } from "../paineis/schema";
import type { CampoConfig, DefWidget } from "./tipos";
import { TIPOS_MAPA } from "../components/mapas/tipos";
import { COLUNAS } from "../components/tabelas/TabelaRecortes";
import { TIPOS_EVENTO } from "../components/eventos/FeedEventos";
import {
  OPCOES_KPI,
  WCandidato,
  WComparativo,
  WEventos,
  WEvolucao,
  WHeatmap,
  WHemiciclo,
  WKpi,
  WLocal,
  WMapa,
  WPlacar,
  WRelogio,
  WRosca,
  WSecao,
  WTabela,
  WTexto,
  WTotais,
} from "./componentes";

/** Campos de aparência/comportamento comuns a todos os widgets */
export const CAMPOS_COMUNS: CampoConfig[] = [
  { chave: "titulo", rotulo: "Título", tipo: "texto" },
  {
    chave: "clique",
    rotulo: "Ao clicar em mapa/tabela",
    tipo: "select",
    opcoes: [
      { value: "filtrar", label: "Filtrar o painel (cross-filtering)" },
      { value: "navegar", label: "Abrir a página do recorte" },
    ],
  },
];

const ddl = (values: [string, string][]) => values.map(([value, label]) => ({ value, label }));

export const REGISTRO: Record<TipoWidget, DefWidget> = {
  placar: {
    tipo: "placar",
    nome: "Placar de candidatos",
    descricao: "Ranking com barras, votos, % dos válidos e selos de situação. Abas de partidos e hemiciclo nos proporcionais.",
    icone: IconListNumbers,
    tamanho: { w: 5, h: 9, minW: 3, minH: 4 },
    padrao: { topN: 0, soEleitos: false, mostrarFotos: true },
    campos: [
      { chave: "topN", rotulo: "Mostrar só os N primeiros (0 = todos)", tipo: "numero", min: 0, max: 100 },
      { chave: "soEleitos", rotulo: "Começar mostrando só eleitos", tipo: "switch" },
      { chave: "mostrarFotos", rotulo: "Mostrar fotos", tipo: "switch" },
    ],
    Componente: WPlacar,
    exporta: "resultados",
  },
  totais: {
    tipo: "totais",
    nome: "Bloco de totais",
    descricao: "Votos válidos em destaque, brancos, nulos, abstenção, comparecimento e % de seções apuradas.",
    icone: IconFileCertificate,
    tamanho: { w: 5, h: 6, minW: 3, minH: 3 },
    padrao: { compacto: false },
    campos: [{ chave: "compacto", rotulo: "Modo compacto", tipo: "switch" }],
    Componente: WTotais,
    exporta: "resultados",
  },
  kpi: {
    tipo: "kpi",
    nome: "KPI único",
    descricao: "Um número grande com a variação em relação a N minutos atrás.",
    icone: IconNumber,
    tamanho: { w: 3, h: 4, minW: 2, minH: 3 },
    padrao: { metrica: "votos_validos", compararMin: 15 },
    campos: [
      { chave: "metrica", rotulo: "Métrica", tipo: "select", opcoes: OPCOES_KPI },
      { chave: "sqcand", rotulo: "Candidato", tipo: "candidato", quando: (c) => String(c.metrica ?? "").startsWith("candidato") },
      { chave: "compararMin", rotulo: "Comparar com há N minutos (0 = não comparar)", tipo: "numero", min: 0, max: 600 },
      { chave: "corDestaque", rotulo: "Cor do número", tipo: "cor" },
    ],
    Componente: WKpi,
    exporta: "resultados",
  },
  mapa: {
    tipo: "mapa",
    nome: "Mapa",
    descricao: "Vencedores, desempenho, comparativo A×B, progresso, locais apurados, comparecimento ou partido mais votado.",
    icone: IconMap2,
    tamanho: { w: 7, h: 12, minW: 3, minH: 6 },
    padrao: { tipo: "vencedores", nivelFilhos: "auto", basemap: "padrao" },
    campos: [
      { chave: "tipo", rotulo: "Tipo de mapa", tipo: "select", opcoes: TIPOS_MAPA.map((t) => ({ value: t.valor, label: t.rotulo })) },
      {
        chave: "nivelFilhos",
        rotulo: "No Brasil, desenhar",
        tipo: "select",
        opcoes: ddl([
          ["auto", "UFs"],
          ["municipio", "Todos os municípios"],
        ]),
      },
      { chave: "candidatoA", rotulo: "Candidato (A)", tipo: "candidato", quando: (c) => c.tipo === "desempenho" || c.tipo === "comparativo" },
      { chave: "candidatoB", rotulo: "Candidato B", tipo: "candidato", quando: (c) => c.tipo === "comparativo" },
      {
        chave: "basemap",
        rotulo: "Mapa de fundo",
        tipo: "select",
        opcoes: ddl([
          ["padrao", "Conforme preferências"],
          ["sim", "Mostrar"],
          ["nao", "Ocultar"],
        ]),
      },
    ],
    Componente: WMapa,
    exporta: "filhos",
  },
  evolucao: {
    tipo: "evolucao",
    nome: "Evolução temporal",
    descricao: "% de cada candidato × horário ou × % de seções, votos ou diferença entre os 2 primeiros, com eventos marcados.",
    icone: IconChartLine,
    tamanho: { w: 6, h: 8, minW: 3, minH: 5 },
    padrao: { eixoX: "t", metrica: "pct", estilo: "linha", topN: 6 },
    campos: [
      { chave: "eixoX", rotulo: "Eixo X", tipo: "select", opcoes: ddl([["t", "Horário"], ["pct_secoes", "% de seções apuradas"]]) },
      { chave: "metrica", rotulo: "Métrica", tipo: "select", opcoes: ddl([["pct", "% dos válidos"], ["votos", "Votos"], ["diferenca", "Diferença 1º − 2º (p.p.)"]]) },
      { chave: "estilo", rotulo: "Estilo", tipo: "select", opcoes: ddl([["linha", "Linha"], ["area", "Área"]]) },
      { chave: "topN", rotulo: "Candidatos exibidos", tipo: "numero", min: 2, max: 20 },
    ],
    Componente: WEvolucao,
  },
  tabela: {
    tipo: "tabela",
    nome: "Tabela de recortes",
    descricao: "Filhos do recorte com vencedor, margem, % apurado e mini-barras. Filtros combináveis e agrupamentos.",
    icone: IconTable,
    tamanho: { w: 12, h: 10, minW: 4, minH: 5 },
    padrao: { mostrarFiltros: true, nivelFilhos: "auto", topN: 0 },
    campos: [
      { chave: "colunas", rotulo: "Colunas", tipo: "multiselect", opcoes: COLUNAS.map((c) => ({ value: c.id, label: c.rotulo })) },
      { chave: "nivelFilhos", rotulo: "No Brasil, listar", tipo: "select", opcoes: ddl([["auto", "UFs"], ["municipio", "Todos os municípios"]]) },
      { chave: "topN", rotulo: "Limitar a N linhas (0 = todas)", tipo: "numero", min: 0, max: 6000 },
      { chave: "mostrarFiltros", rotulo: "Mostrar barra de filtros", tipo: "switch" },
    ],
    Componente: WTabela,
    exporta: "filhos",
  },
  comparativo: {
    tipo: "comparativo",
    nome: "Comparativo lado a lado",
    descricao: "2 a 4 recortes lado a lado, ou candidatos comparados nos filhos do recorte.",
    icone: IconColumns,
    tamanho: { w: 8, h: 8, minW: 4, minH: 5 },
    padrao: { modo: "recortes", recortes: ["uf:sp", "uf:mg", "uf:rj"] },
    campos: [
      { chave: "modo", rotulo: "Comparar", tipo: "select", opcoes: ddl([["recortes", "Recortes"], ["candidatos", "Candidatos"]]) },
      { chave: "recortes", rotulo: "Recortes (até 4)", tipo: "recortes", quando: (c) => c.modo !== "candidatos" },
      { chave: "candidatos", rotulo: "Candidatos (até 4)", tipo: "candidatos", quando: (c) => c.modo === "candidatos" },
    ],
    Componente: WComparativo,
  },
  hemiciclo: {
    tipo: "hemiciclo",
    nome: "Hemiciclo / vagas",
    descricao: "Vagas por partido/federação (cargos proporcionais), conforme publicado pelo TSE.",
    icone: IconChartArcs,
    tamanho: { w: 6, h: 9, minW: 3, minH: 5 },
    padrao: {},
    campos: [],
    Componente: WHemiciclo,
    exporta: "resultados",
  },
  rosca: {
    tipo: "rosca",
    nome: "Rosca de distribuição",
    descricao: "Distribuição dos votos entre os candidatos (opcionalmente com brancos e nulos).",
    icone: IconChartDonut,
    tamanho: { w: 4, h: 8, minW: 3, minH: 5 },
    padrao: { topN: 6, incluirBrancosNulos: false },
    campos: [
      { chave: "topN", rotulo: "Candidatos antes de “Outros”", tipo: "numero", min: 1, max: 20 },
      { chave: "incluirBrancosNulos", rotulo: "Incluir brancos e nulos", tipo: "switch" },
    ],
    Componente: WRosca,
    exporta: "resultados",
  },
  heatmap: {
    tipo: "heatmap",
    nome: "Heatmap de progresso por UF",
    descricao: "Cartograma das UFs colorido pela % de seções apuradas (ou comparecimento).",
    icone: IconGridDots,
    tamanho: { w: 5, h: 9, minW: 3, minH: 6 },
    padrao: { metrica: "pct_secoes" },
    campos: [
      { chave: "metrica", rotulo: "Métrica", tipo: "select", opcoes: ddl([["pct_secoes", "% de seções apuradas"], ["pct_comparecimento", "% de comparecimento"]]) },
    ],
    Componente: WHeatmap,
  },
  eventos: {
    tipo: "eventos",
    nome: "Feed de eventos",
    descricao: "Viradas, marcos da apuração, eleitos e 2º turno em tempo real.",
    icone: IconCalendarEvent,
    tamanho: { w: 4, h: 9, minW: 3, minH: 4 },
    padrao: { limite: 50, soRecorte: false, soCargo: false },
    campos: [
      { chave: "tipos", rotulo: "Tipos de evento (vazio = todos)", tipo: "multiselect", opcoes: TIPOS_EVENTO },
      { chave: "limite", rotulo: "Quantidade máxima", tipo: "numero", min: 5, max: 200 },
      { chave: "soCargo", rotulo: "Só do cargo do filtro", tipo: "switch" },
      { chave: "soRecorte", rotulo: "Só do recorte do filtro", tipo: "switch" },
    ],
    Componente: WEventos,
  },
  candidato: {
    tipo: "candidato",
    nome: "Card de candidato",
    descricao: "Foto, número, partido, vice/suplentes, votos e selo de situação.",
    icone: IconUserCircle,
    tamanho: { w: 5, h: 5, minW: 3, minH: 4 },
    padrao: {},
    campos: [{ chave: "sqcand", rotulo: "Candidato", tipo: "candidato" }],
    Componente: WCandidato,
  },
  local: {
    tipo: "local",
    nome: "Local de votação",
    descricao: "Mini-mapa, endereço e lista de seções com status.",
    icone: IconSchool,
    tamanho: { w: 6, h: 11, minW: 3, minH: 6 },
    padrao: {},
    campos: [{ chave: "localId", rotulo: "Local (vazio = usa o filtro)", tipo: "local" }],
    Componente: WLocal,
  },
  secao: {
    tipo: "secao",
    nome: "Detalhe de seção (BU)",
    descricao: "Boletim de urna decodificado: votos por cargo, horário, hash e assinatura.",
    icone: IconBuildingCommunity,
    tamanho: { w: 6, h: 11, minW: 3, minH: 6 },
    padrao: {},
    campos: [{ chave: "secaoId", rotulo: "Seção (vazio = usa o filtro)", tipo: "secao" }],
    Componente: WSecao,
  },
  relogio: {
    tipo: "relogio",
    nome: "Relógio / contagem regressiva",
    descricao: "Horário de Brasília ou contagem até um horário (ex.: início da divulgação).",
    icone: IconClock,
    tamanho: { w: 3, h: 4, minW: 2, minH: 3 },
    padrao: { modo: "relogio" },
    campos: [
      { chave: "modo", rotulo: "Modo", tipo: "select", opcoes: ddl([["relogio", "Relógio de Brasília"], ["contagem", "Contagem regressiva"]]) },
      { chave: "alvo", rotulo: "Contar até", tipo: "datahora", quando: (c) => c.modo === "contagem" },
      { chave: "rotulo", rotulo: "Rótulo", tipo: "texto" },
    ],
    Componente: WRelogio,
  },
  texto: {
    tipo: "texto",
    nome: "Texto / anotação",
    descricao: "Anotações em markdown simples.",
    icone: IconNotes,
    tamanho: { w: 4, h: 4, minW: 2, minH: 2 },
    padrao: { texto: "## Anotações\n- Acompanhar a virada em **MG**\n- Abrir o placar do Senado" },
    campos: [{ chave: "texto", rotulo: "Texto (markdown)", tipo: "textarea" }],
    Componente: WTexto,
  },
};

export const CATALOGO = Object.values(REGISTRO);
